"""Plot each colour channel of the working image side by side."""

from __future__ import annotations

import tkinter as tk

from PIL import Image, ImageDraw, ImageFont

from forensics_app.core import ImageDocument
from .base import ForensicsTool, ToolResult

PANEL_SIZE = (320, 320)
MARGIN = 12
TITLE_HEIGHT = 28
BACKGROUND = "white"
TEXT_COLOUR = "black"
PLOT_MARKER = "forensics_channel_plot"


def split_channels(image: Image.Image) -> list[tuple[str, Image.Image]]: #input image, output list of tuples (channel name, channel image)
    """Return ``(name, channel)`` pairs; each channel is an 8-bit ``L`` image.

    An alpha channel is only kept when some pixel is actually transparent.
    """
    if image.mode not in ("L", "LA", "RGB", "RGBA", "CMYK", "YCbCr", "LAB", "HSV"):
        image = image.convert("RGBA" if "A" in image.getbands() or "transparency" in image.info else "RGB") #if not one of the supported types, convert
    channels = list(zip(image.getbands(), image.split()))
    return [(name, band) for name, band in channels if name != "A" or band.getextrema() != (255, 255)]


def _title_font() -> ImageFont.ImageFont | ImageFont.FreeTypeFont:
    try:
        return ImageFont.load_default(size=16)
    except TypeError:  # Pillow < 10.1 has no ``size`` argument
        return ImageFont.load_default()


def plot_channels(channels: list[tuple[str, Image.Image]]) -> Image.Image: #gets the channel list from split channels (channel name, channel image) and creates a plot with it
    """Render the channels as a row of labelled grayscale panels in one RGB image."""
    previews = []
    for name, channel in channels:
        preview = channel.copy()
        preview.thumbnail(PANEL_SIZE, Image.Resampling.LANCZOS)  #resize
        previews.append((name, preview))

    panel_width = max(preview.width for _, preview in previews)
    panel_height = max(preview.height for _, preview in previews)
    width = MARGIN + len(previews) * (panel_width + MARGIN)
    height = MARGIN + TITLE_HEIGHT + panel_height + MARGIN

    plot = Image.new("RGB", (width, height), BACKGROUND)
    draw = ImageDraw.Draw(plot)
    font = _title_font()
    for index, (name, preview) in enumerate(previews):
        left = MARGIN + index * (panel_width + MARGIN)
        draw.text(
            (left + panel_width / 2, MARGIN + TITLE_HEIGHT / 2),
            f"Channel {name}",
            fill=TEXT_COLOUR,
            font=font,
            anchor="mm",
        )
        x = left + (panel_width - preview.width) // 2
        y = MARGIN + TITLE_HEIGHT + (panel_height - preview.height) // 2
        plot.paste(preview.convert("RGB"), (x, y))
        draw.rectangle((x - 1, y - 1, x + preview.width, y + preview.height), outline=TEXT_COLOUR)
    return plot


class ChannelSplitTool(ForensicsTool):
    tool_id = "channel_split"
    title = "Split image channels"
    category = "Set2"
    description = "Plot each colour channel of the image as a separate grayscale panel."

    def run(self, parent: tk.Misc, document: ImageDocument) -> ToolResult:
        assert document.current is not None  # guarded by the main window
        previous_details = document.current.info.get(PLOT_MARKER)  #uses the plots info to check if it was already generated by this function to not nest 
        if previous_details is not None:
            # Splitting our own plot again would nest plots inside plots on every click.
            return ToolResult(
                message="The channel plot is already shown; undo to return to the image.",
                details=previous_details,
            )
        channels = split_channels(document.current)
        details = {
            "Operation": "Channel split",
            "Mode": document.current.mode,
            "Channels": ", ".join(name for name, _ in channels),
        }
        plot = plot_channels(channels)
        plot.info[PLOT_MARKER] = details  # survives the copies made by ImageDocument
        return ToolResult(message=f"Plotted {len(channels)} channel(s).", image=plot, details=details)
